# Generated by Django 3.2.12 on 2023-04-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform_model',
            name='leave_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
