# Generated by Django 3.2.12 on 2023-04-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0002_leaveform_model_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform_model',
            name='reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveform_model',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Emergency Leave', 'Emergency Leave'), ('Maternity Leave', 'Maternity Leave'), ('Bereavement Leave', 'Bereavement Leave'), ('Sabbatical Leave', 'Sabbatical Leave'), ('Compensatory Leave', 'Compensatory Leave')], max_length=100),
        ),
    ]
