# Generated by Django 3.2.12 on 2023-04-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0003_auto_20230412_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform_model',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Emergency Leave', 'Emergency Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Bereavement Leave', 'Bereavement Leave'), ('Sabbatical Leave', 'Sabbatical Leave'), ('Compensatory Leave', 'Compensatory Leave')], max_length=100),
        ),
    ]
