# Generated by Django 3.2.12 on 2023-04-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0004_alter_leaveform_model_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='addholidays_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=100)),
                ('festival_name', models.CharField(max_length=100)),
            ],
        ),
    ]
