# Generated by Django 3.2.12 on 2023-04-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0005_addholidays_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addholidays_model',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
