# Generated by Django 3.2.12 on 2023-04-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0007_alter_addholidays_model_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform_model',
            name='leave_days',
        ),
    ]
