# Generated by Django 3.2.12 on 2023-04-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0008_remove_leaveform_model_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform_model',
            name='leave_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
