# Generated by Django 4.1.7 on 2023-04-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_leave_form_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('FINANCE', 'FINANCE'), ('SALES', 'SALES'), ('SOFTWARE DEVELOPER', 'SOFTWARE DEVELOPER'), ('HR', 'HR')], max_length=100),
        ),
    ]
