# Generated by Django 4.1.7 on 2023-04-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_form',
            name='remaining_days',
            field=models.CharField(default='', max_length=100),
        ),
    ]
