# Generated by Django 4.1.7 on 2023-04-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_leave_form_remaining_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_form',
            name='reason',
            field=models.CharField(default='', max_length=500),
        ),
    ]
