# Generated by Django 4.1.7 on 2023-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_leave_form_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_form',
            name='number_of_days',
            field=models.IntegerField(default=0),
        ),
    ]
