# Generated by Django 4.1.7 on 2023-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_leave_form_remaining_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_form',
            name='reason',
            field=models.CharField(default='No reason', max_length=500),
        ),
    ]
