# Generated by Django 4.1.7 on 2023-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_leave_form_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_form',
            name='remaining_days',
            field=models.IntegerField(default=18, max_length=100),
        ),
    ]
