# Generated by Django 4.1.7 on 2023-04-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_leave_form_remaining_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=100)),
                ('festival_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
