# Generated by Django 4.1.7 on 2023-04-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_holiday_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_form',
            name='remaining_days',
            field=models.IntegerField(default=18),
        ),
    ]
